#
# SPDX-License-Identifier: MIT
#
# Copyright (C) 2025 Daniel Bourdrez. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree or at
# https://spdx.org/licenses/MIT.html
#

---

name: Lint Suite

on:
  workflow_call:
    inputs:
      gofmt:
        description: 'Run gofmt to ensure Go sources are formatted'
        required: false
        type: boolean
        default: false
      super-linter:
        description: 'Run GitHub Super-Linter'
        required: false
        type: boolean
        default: false
      super-linter-validate-all-codebase:
        description: 'Whether to validate the entire codebase with Super-Linter'
        required: false
        type: boolean
      super-linter-enabled-linters:
        description: >-
          Comma-separated list of linters to enable explicitly
          (maps to VALIDATE_* env vars)
        required: false
        type: string
      super-linter-rules-path:
        description: 'Path to custom linter rules for Super-Linter'
        required: false
        type: string

permissions: { }

jobs:
  GoFmt:
    name: Golang Format Check (go fmt)
    if: ${{ inputs.gofmt }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            go.dev:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443

      - name: Check out repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - name: Init go
        uses: bytemare/actions/init-go@d693c2cf1d83d323e3178be93793b06b46208148

      - name: Check formatting
        run: |
          if [[ -n "$(gofmt -l .)" ]]; then
            echo "The following files are not formatted correctly:"
            gofmt -l .
            exit 1
          fi

  SuperLinter:
    if: ${{ inputs['super-linter'] }}
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ./.github/workflows/super-linter.yaml
    with:
      validate-all-codebase: ${{ inputs['super-linter-validate-all-codebase'] }}
      enabled_linters: ${{ inputs['super-linter-enabled-linters'] }}
      linter-rules-path: ${{ inputs['super-linter-rules-path'] }}
